### ISSUE TITLE
execute

### ISSUE THREAD

**Issue by cutefulf** [zhangyp15/BEVerse#12]

**Comment by cutefulf** [comment]
dear author，thank you for your grate work. I follow the installation guide and succesfully install the required packages. but when I execute the python tools/create_data.py nuscenes ... to generate data. I got the failure below:
Traceback (most recent call last):
  File "tools/create_data.py", line 8, in <module>
    from tools.data_converter import nuscenes_converter as nuscenes_converter
  File "/home/coolwin.fu/code/BEVerse-main/tools/data_converter/nuscenes_converter.py", line 13, in <module>
    from mmdet3d.core.bbox.box_np_ops import points_cam2img
  File "/home/coolwin.fu/code/BEVerse-main/mmdet3d/core/__init__.py", line 2, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/home/coolwin.fu/code/BEVerse-main/mmdet3d/core/anchor/__init__.py", line 2, in <module>
    from mmdet.core.anchor import build_prior_generator
  File "/home/coolwin.fu/miniconda3/envs/mmlab/lib/python3.8/site-packages/mmdet/core/__init__.py", line 2, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/home/coolwin.fu/miniconda3/envs/mmlab/lib/python3.8/site-packages/mmdet/core/bbox/__init__.py", line 7, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "/home/coolwin.fu/miniconda3/envs/mmlab/lib/python3.8/site-packages/mmdet/core/bbox/samplers/__init__.py", line 9, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "/home/coolwin.fu/miniconda3/envs/mmlab/lib/python3.8/site-packages/mmdet/core/bbox/samplers/score_hlr_sampler.py", line 2, in <module>
    from mmcv.ops import nms_match
  File "/home/coolwin.fu/miniconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .ball_query import ball_query
  File "/home/coolwin.fu/miniconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/ops/ball_query.py", line 7, in <module>
    ext_module = ext_loader.load_ext('_ext', ['ball_query_forward'])
  File "/home/coolwin.fu/miniconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/coolwin.fu/miniconda3/envs/mmlab/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/coolwin.fu/miniconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail19maybe_wrap_dim_slowEllb
