### ISSUE TITLE
if you can tell me how to configurate dataset path? thanks

### ISSUE THREAD

**Issue by xiaowhite-22** [zhangyp15/BEVerse#18]
Traceback (most recent call last):
  File "/home/chenyi/下载/BEVerse/tools/train.py", line 254, in <module>
    main()
  File "/home/chenyi/下载/BEVerse/tools/train.py", line 217, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/chenyi/下载/BEVerse/mmdet3d/datasets/builder.py", line 37, in build_dataset
    dataset = CBGSDataset(build_dataset(cfg['dataset'], default_args))
  File "/home/chenyi/下载/BEVerse/mmdet3d/datasets/builder.py", line 41, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/chenyi/anaconda3/envs/beverse/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: MTLEgoNuScenesDataset: [Errno 2] No such file or directory: 'data/nuscenes_infos/nuscenes_infos_train.pkl'

**Comment by huoxingsenlin** [comment]
Hello! Have you solved it yet?

> Traceback (most recent call last):回溯 （最近调用最后）： File "/home/chenyi/下载/BEVerse/tools/train.py", line 254, in 文件 “/home/chenyi/下载/BEVerse/tools/train.py”，第 254 行，在 main()  主（） File "/home/chenyi/下载/BEVerse/tools/train.py", line 217, in main文件 “/home/chenyi/下载/BEVerse/tools/train.py”，第 217 行，在 main 中 datasets = [build_dataset(cfg.data.train)]数据集 = [build_dataset（cfg.data.train）] File "/home/chenyi/下载/BEVerse/mmdet3d/datasets/builder.py", line 37, in build_dataset文件 “/home/chenyi/下载/BEVerse/mmdet3d/datasets/builder.py”，第 37 行，build_dataset dataset = CBGSDataset(build_dataset(cfg['dataset'], default_args))数据集 = CBGSDataset（build_dataset（cfg['dataset']， default_args）） File "/home/chenyi/下载/BEVerse/mmdet3d/datasets/builder.py", line 41, in build_dataset文件 “/home/chenyi/下载/BEVerse/mmdet3d/datasets/builder.py”，第 41 行，build_dataset dataset = build_from_cfg(cfg, DATASETS, default_args)数据集 = build_from_cfg（cfg， 数据集， default_args） File "/home/chenyi/anaconda3/envs/beverse/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg文件 “/home/chenyi/anaconda3/envs/beverse/lib/python3.7/site-packages/mmcv/utils/registry.py”，第 55 行，build_from_cfg raise type(e)(f'{obj_cls.**name**}: {e}')raise type（e）（f'{**obj_cls.name**}： {e}'） FileNotFoundError: MTLEgoNuScenesDataset: [Errno 2] No such file or directory: 'data/nuscenes_infos/nuscenes_infos_train.pkl'FileNotFoundError： MTLEgoNuScenesDataset： [Errno 2] 没有这样的文件或目录： 'data/nuscenes_infos/nuscenes_infos_train.pkl'

Hello! Have you solved it yet?
